### PR TITLE
feat: lowercase brand issuer name

### LINKED ISSUE #16: stATOM vs STATOM in agoricNames.brand
In #15 `stATOM` is used for `proposedName`, but "The asset keyword must begin with an uppercase letter, so `STATOM` is used". 

Unfortunately, the `keyword` is used in more places than it should be; in particular, in `agoricNames`.

### PR DESCRIPTION
**Pull request by 0xpatrickdev**
- addresses #16
- incorporates changes from Agoric/agoric-sdk#8229 in my branch, `pc/statom-vault-proposal-issuerName`
    - versus the previous head used: https://github.com/0xpatrickdev/agoric-sdk/compare/pc/statom-vault-proposal...0xpatrickdev:agoric-sdk:pc/statom-vault-proposal-issuerName?expand=1
    - versus main: https://github.com/Agoric/agoric-sdk/compare/master...0xpatrickdev:pc/statom-vault-proposal-issuerName?expand=1

fixes: #16

### CODE REVIEW

**Comment by dckc** [comment]
I think we don't actually want the provisionPool work-around...

 - https://github.com/Agoric/agoric-sdk/pull/8229/commits/e6b0ab8d6831e67bb0e05f8995738322c451865d

It unnecessarily makes the `issuerName` in `agoricNames.vbankAsset` different from elsewhere.

Maybe it's OK for testing. hm.

**Review by dckc — APPROVED** [review]
I'd rather leave out the provisionPool work-around, but maybe it's OK for now.

**Comment by 0xpatrickdev** [comment]
> I'd rather leave out the provisionPool work-around, but maybe it's OK for now.

Addressed in [85ac4a8](https://github.com/0xpatrickdev/agoric-vault-collateral-proposal/pull/17/commits/85ac4a8db8e5082985599e0bb705e8369e194537) and [4838bc5](https://github.com/Agoric/agoric-sdk/commit/4838bc51b877af4196139a1af1e71d56b8aa561b)

This results in an error being thrown, `SwingSet: xsnap: v29: Error: keyword "stATOM" must be an ascii identifier starting with upper case`, but per discussion during the pairing session this is OK. 

_For transparency I only verified that `manager1` is present in the `published.vaultFactory.managers` query, and did not try the full flow yet_

**Comment by dckc** [comment]
re the updated bundles, I just confirmed them by checking out agoric-sdk `4838bc51b` and running `yarn build:add-stATOM-proposal` in `packages/inter-protocol`:

```
b1-1c8e93cc80b28b2cf6b1252e9b6edb0253a1f962889f8a255397b43984950a263dd9c9efd82aee5744b46e7bd57ff1c733030e9f4dc8da9b355b185a59687862.json
b1-8fb229296073327ed26d2a1ac56eda2bdc70c99d68621895a88f6cc09bce2defa3bd0894e97950e5a0696388193279c8f6b9399809611f8fec3ef5aeed355ba5.json
b1-c185bf3b0d7cf940a4f6d6ca1cd74a5d0f5ff330be1cfceaa6c5e4204ba1196e92444e086bf03573371216f41941d1b0fc8560984e2da09f2edd412e46dd62e3.json
b1-e4ba9cb60b5b59d4d4618710991fe8a503dd4a07c7f17029a342ccb41893bc961ae63bcb0e2c20e4bc2415c9755f090f7761751cdd00b85762902b357a48c5cf.json
```

**Comment by dckc** [comment]
I presume you don't mind if I go ahead and merge this, having tested it on ollinet.

**Pull request merged**
